config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
    # sessions: 'users/sessions'
  }

  resources :categories, only: %i[index show] do
    resources :articles, only: :index
  end

  resources :articles, only: :show do
    resources :comments, only: %i[index create destroy], module: :articles
  end

  get '/articles', to: redirect('/categories')

  resources :tickets, except: %i[edit destroy] do
    resources :comments, only: %i[index create destroy], module: :tickets
  end

  resources :users

  resources :comments

  namespace :supports do
    resources :categories do
      resources :articles
    end
    resources :tags
    resources :articles

    resources :tickets
  end

  resources :marks
  # resources :tags
  # resources :tickets
  # resources :articles
  # resources :categories
  get 'page/contacts'
  get 'page/terms'
  get 'page/about'
  root 'categories#index'
end

app/models/mark.rb
class Mark < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/controllers/marks_controller.rb
class MarksController < ApplicationController
  load_and_authorize_resource
  before_action :set_mark, only: [:show, :edit, :update, :destroy]

  # GET /marks
  # GET /marks.json
  def index
    @marks = Mark.all
  end

  # GET /marks/1
  # GET /marks/1.json
  def show
  end

  # GET /marks/new
  def new
    @mark = Mark.new
  end

  # GET /marks/1/edit
  def edit
  end

  # POST /marks
  # POST /marks.json
  def create
    @mark = Mark.new(mark_params)
    @mark.user = User.first

    respond_to do |format|
      if @mark.save
        format.html { redirect_to @mark, notice: 'Mark was successfully created.' }
        format.json { render :show, status: :created, location: @mark }
      else
        format.html { render :new }
        format.json { render json: @mark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /marks/1
  # PATCH/PUT /marks/1.json
  def update
    respond_to do |format|
      if @mark.update(mark_params)
        format.html { redirect_to @mark, notice: 'Mark was successfully updated.' }
        format.json { render :show, status: :ok, location: @mark }
      else
        format.html { render :edit }
        format.json { render json: @mark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /marks/1
  # DELETE /marks/1.json
  def destroy
    @mark.destroy
    respond_to do |format|
      format.html { redirect_to marks_url, notice: 'Mark was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mark
      @mark = Mark.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mark_params
      params.require(:mark).permit(:user_id, :article_id, :value)
    end
end

app/helpers/marks_helper.rb
module MarksHelper
end

app/views/marks/_form.html.slim
= form_for @mark do |f|
  - if @mark.errors.any?
    #error_explanation
      h2 = "#{pluralize(@mark.errors.count, "error")} prohibited this mark from being saved:"
      ul
        - @mark.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :user
    = f.text_field :user
  .field
    = f.label :article
    = f.text_field :article
  .field
    = f.label :value
    = f.check_box :value
  .actions = f.submit

app/views/marks/edit.html.slim
h1 Editing mark

== render 'form'

=> link_to 'Show', @mark
'|
=< link_to 'Back', marks_path

app/views/marks/index.html.slim
h1 Listing marks

table
  thead
    tr
      th User
      th Article
      th Value
      th
      th
      th

  tbody
    - @marks.each do |mark|
      tr
        td = mark.user.email
        td = mark.article.title
        td = mark.value
        td = link_to 'Show', mark
        td = link_to 'Edit', edit_mark_path(mark)
        td = link_to 'Destroy', mark, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Mark', new_mark_path

app/views/marks/new.html.slim
h1 New mark

== render 'form'

= link_to 'Back', marks_path

app/views/marks/show.html.slim
p#notice = notice

p
  strong User:
  = @mark.user.email
p
  strong Article:
  = @mark.article.title
p
  strong Value:
  = @mark.value

=> link_to 'Edit', edit_mark_path(@mark)
'|
=< link_to 'Back', marks_path