config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
    # sessions: 'users/sessions'
  }

  resources :categories, only: %i[index show] do
    resources :articles, only: :index
  end

  resources :articles, only: :show do
    resources :comments, only: %i[index create destroy], module: :articles
  end

  get '/articles', to: redirect('/categories')

  resources :tickets, except: %i[edit destroy] do
    resources :comments, only: %i[index create destroy], module: :tickets
  end

  resources :users

  resources :comments

  namespace :supports do
    resources :categories do
      resources :articles
    end
    resources :tags
    resources :articles

    resources :tickets
  end

  resources :marks
  # resources :tags
  # resources :tickets
  # resources :articles
  # resources :categories
  get 'page/contacts'
  get 'page/terms'
  get 'page/about'
  root 'categories#index'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  belongs_to :user

  validates :user, presence: true
  validates :commentable_type, presence: true
  validates :commentable_id, presence: true
  validates :body, presence: true
  validates :body, inclusion: false
end

app/controllers/articles/comments_controller.rb
class Articles::CommentsController < CommentsController
  before_action :set_commentable

  private

  def set_commentable
    @commentable = Article.find(params[:article_id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    # @comment = Comment.new(comment_params)
    @comment = @commentable.comments.new comment_params
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @commentable, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @commentable, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:commentable_id, :commentable_type, :body, :published)
    end
end

app/controllers/tickets/comments_controller.rb
class Tickets::CommentsController < CommentsController
  before_action :set_commentable

  private

  def set_commentable
    @commentable = Ticket.find(params[:ticket_id])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comments.html.slim
- comments.each do |comment|
  = comment.user.email
  br
  = comment.body
  br
  - if user_signed_in?
    -if comment.user.id == current_user.id
      = link_to 'Destroy', [comment.commentable, comment], data: { confirm: 'Are you sure?' }, method: :delete
  br
  / = comment.commentable

app/views/comments/_form.html.slim
/ = form_for [commentable, Comment.new] do |form|
/   = form.text_area :body, placeholder: "Ваше сообщение", class: "comment-text-area"
/   = form.submit id: "comment-submit", value: "Отправить"

.m-task__comments-input
  = form_for [commentable, Comment.new] do |form|
    = form.text_area :body, placeholder: "Ваш комментарий", class: "form-control m-task__comments-textarea js-auto-size"
    .d-flex.align-items-center.justify-content-between
      = form.submit id: "comment-submit", value: "Отправить", class: 'btn btn-info'

/ = form_for [commentable, Comment.new] do |f|
/   - if @comment.errors.any?
/     #error_explanation
/       h2 = "#{pluralize(@comment.errors.count, "error")} prohibited this comment from being saved:"
/       ul
/         - @comment.errors.full_messages.each do |message|
/           li = message
/
/   .field
/     = f.label :commentable
/     = f.text_field :commentable
/   .field
/     = f.label :body
/     = f.text_field :body
/   .field
/     = f.label :published
/     = f.check_box :published
/   .actions = f.submit

app/views/comments/edit.html.slim
h1 Editing comment

== render 'form'

=> link_to 'Show', @comment
'|
=< link_to 'Back', comments_path

app/views/comments/index.html.slim
h1 Listing comments

table
  thead
    tr
      th User
      th Commentable
      th Body
      th Published
      th
      th
      th

  tbody
    - @comments.each do |comment|
      tr
        td = comment.user.email
        td = comment.commentable
        td = comment.body
        td = comment.published
        td = link_to 'Show', comment
        td = link_to 'Edit', edit_comment_path(comment)
        td = link_to 'Destroy', comment, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Comment', new_comment_path

app/views/comments/new.html.slim
h1 New comment

== render 'form'

= link_to 'Back', comments_path

app/views/comments/show.html.slim
p#notice = notice

p
  strong Commentable:
  = @comment.commentable
p
  strong Body:
  = @comment.body
p
  strong Published:
  = @comment.published

=> link_to 'Edit', edit_comment_path(@comment)
'|
=< link_to 'Back', comments_path