config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
    # sessions: 'users/sessions'
  }

  resources :categories, only: %i[index show] do
    resources :articles, only: :index
  end

  resources :articles, only: :show do
    resources :comments, only: %i[index create destroy], module: :articles
  end

  get '/articles', to: redirect('/categories')

  resources :tickets, except: %i[edit destroy] do
    resources :comments, only: %i[index create destroy], module: :tickets
  end

  resources :users

  resources :comments

  namespace :supports do
    resources :categories do
      resources :articles
    end
    resources :tags
    resources :articles

    resources :tickets
  end

  resources :marks
  # resources :tags
  # resources :tickets
  # resources :articles
  # resources :categories
  get 'page/contacts'
  get 'page/terms'
  get 'page/about'
  root 'categories#index'
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # has_and_belongs_to_many :roles, join_table: :users_roles
  has_many :articles, dependent: :destroy
  has_many :requests, class_name: 'Ticket', foreign_key: 'user_id', dependent: :destroy
  has_many :tickets,  class_name: 'Ticket', foreign_key: 'moderator_id', dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :marks

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  # validates :password,  presence: true
  # validates :role,      presence: true

  after_create :assign_default_role

  def assign_default_role
    add_role(:user) if roles.blank?
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super do |resource|
  #     resource.add_role 'user'
  #     resource.save
  #   end
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    # devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email role_id])
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :role_id)
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name email role_id])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email,role_ids: [])
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.slim
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      h2 = "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      ul
        - @user.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :email
    = f.email_field :email
  .field
    = f.label :role
    = f.collection_select(:role_ids, Role.all, :id, :name, {prompt: "Выберите роль"})
  .actions = f.submit

app/views/users/_menu.html.slim
.m-social-profile__nav
  h1
    | Личный кабинет
  br
  br
  .m-social-profile__nav-section
    h6.m-social-profile__nav-section-heading
      |  Обращения
    ul.m-social-profile__nav-menu
      li class="m-social-profile__nav-menu-item #{ current_page?(tickets_path) ? 'is-active' : ''}"
        / = link_to 'Мои обращения', tickets_path, class: 'm-social-profile__nav-menu-link'
        /   span.iconfont.iconfont-individual.m-social-profile__nav-menu-icon
        a.m-social-profile__nav-menu-link[href="#{tickets_path}"]
          span.iconfont.iconfont-individual.m-social-profile__nav-menu-icon
          |  Мои обращения
      li class="m-social-profile__nav-menu-item  #{ current_page?(new_ticket_path) ? 'is-active' : ''}"
        a.m-social-profile__nav-menu-link[href="#{new_ticket_path}"]
          span.iconfont.iconfont-profile-history.m-social-profile__nav-menu-icon
          |  Создать новое обращение
  .m-social-profile__nav-section
    h6.m-social-profile__nav-section-heading
      |  Профиль
    ul.m-social-profile__nav-menu
      li class="m-social-profile__nav-menu-item #{ current_page?(user_path current_user) ? 'is-active' : ''}"
        a.m-social-profile__nav-menu-link[href="#{user_path current_user}"]
          span.iconfont.iconfont-document.m-social-profile__nav-menu-icon
          |  Мои данные
      li class="m-social-profile__nav-menu-item #{ current_page?(edit_user_registration_path) ? 'is-active' : ''}"
        a.m-social-profile__nav-menu-link[href="#{edit_user_registration_path}"]
          span.iconfont.iconfont-profile-edit.m-social-profile__nav-menu-icon
          |  Редактировать данные

app/views/users/edit.html.slim
h1 Editing user

== render 'form'

=> link_to 'Show', @user
'|
=< link_to 'Back', users_path

app/views/users/index.html.slim
h1 Listing users

table
  thead
    tr
      th
      th
      th
      th
      th
      th

  tbody
    - @users.each do |user|
      tr
        td = user.name
        td = user.email
        td = user.roles.map { |role| role.name }.split(', ')
        td = link_to 'Show', user
        td = link_to 'Edit', edit_user_path(user)
        td = link_to 'Destroy', user, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New User', new_user_path

app/views/users/new.html.slim
h1 New user

== render 'form'

= link_to 'Back', users_path

app/views/users/show.html.slim
p#notice = notice

h1
  | User

p
  strong Email:
  = @user.email
p
  strong Role:
  = @user.roles

=> link_to 'Edit', edit_user_path(@user)
=> link_to 'Edit', edit_user_registration_path
'|
=< link_to 'Back', users_path