config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
    # sessions: 'users/sessions'
  }

  resources :categories, only: %i[index show] do
    resources :articles, only: :index
  end

  resources :articles, only: :show do
    resources :comments, only: %i[index create destroy], module: :articles
  end

  get '/articles', to: redirect('/categories')

  resources :tickets, except: %i[edit destroy] do
    resources :comments, only: %i[index create destroy], module: :tickets
  end

  resources :users

  resources :comments

  namespace :supports do
    resources :categories do
      resources :articles
    end
    resources :tags
    resources :articles

    resources :tickets
  end

  resources :marks
  # resources :tags
  # resources :tickets
  # resources :articles
  # resources :categories
  get 'page/contacts'
  get 'page/terms'
  get 'page/about'
  root 'categories#index'
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :parent, class_name: 'Category', optional: true
  has_many :children, class_name: 'Category', foreign_key: 'parent_id'
  has_many :articles

  validates :title,     presence: true,   length:       { in: 2..50 }
  validates :level,     presence: true,   numericality: { only_integer: true }
  # validates :parent,    presence: true
  validates :published, inclusion: { in: [true, false] }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  load_and_authorize_resource
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @categories = Category.all
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:title, :level, :parent_id, :published)
    end
end

app/controllers/supports/categories_controller.rb
class Supports::CategoriesController < CategoriesController
  load_and_authorize_resource
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to [:supports, @category], notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to [:supports, @category], notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to supports_categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:title, :level, :parent_id, :published)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/index.html.slim
.container-fluid.container-fh.l-2column
  .m-content
    .row
      - @categories.each do |category|
        .col-lg-4.mb-5
          h2.m-task__name
            = link_to category.title, category, class: 'm-nav__menu-link'
          ul.m-mail__channels
            - category.articles.each do |article|
              li
                = link_to article.title, article, class: 'link-info'


/ h1 Listing categories
/
/ table
/   thead
/     tr
/       th Title
/       / th Level
/       / th Parent
/       / th Published
/       / th
/       / th
/       / th
/
/   tbody
/     - @categories.each do |category|
/       tr
/         / td = category.title
/         td = link_to category.title, category
/         / td = category.level
/         / td = category.parent.title if category.parent
/         / td = category.published
/         / td = link_to 'Show', category
/         / td = link_to 'Edit', edit_category_path(category)
/         / td = link_to 'Destroy', category, data: { confirm: 'Are you sure?' }, method: :delete
/
/ br

/ = link_to 'New Category', new_category_path

app/views/categories/show.html.slim
.container-fluid.container-fh.l-2column
  .m-nav.col-1
    .m-nav__side-top
      h5.m-content__heading
        = link_to 'Разделы', root_path
      br
      ul.m-nav__menu
        - @categories.each do |category|
          li class="m-nav__menu-item #{ category == @category ? 'is-active' : ''}"
            = link_to category.title, category, class: 'm-nav__menu-link'
  .m-content
    ol.breadcrumb
      li.breadcrumb-item
        a[href="#"]
          | Главная
      li.breadcrumb-item.active
        | Регистрация и вход
    h2.m-task__name
      | Регистрация и вход
    .row
      - @category.articles.each do |article|
        .col-lg-6
          .m-task__desc
            .m-task__desc-header
              h3.m-task__desc-heading
                = link_to article.title, article_path(article), class: 'link-info'
                / a.link-info[href="/support_app_layout/article.html"]
                /   | Регистрация
            .m-task__desc-text
              |  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.



/ p#notice = notice
/
/ p
/   strong Title:
/   = @category.title
/ p
/   strong Articles:
/   br
/   - @category.articles.each do |article|
/     = link_to article.title, article_path(article)
/     br
/ / p
/ /   strong Level:
/ /   = @category.level
/ / p
/ /   strong Parent:
/ /   = @category.parent
/ / p
/ /   strong Published:
/ /   = @category.published
/
/ / => link_to 'Edit', edit_category_path(@category)
/ '|
/ =< link_to 'Back', categories_path